name: nauka-zdajmature-app
region: lon
services:
- dockerfile_path: Dockerfile.deployment
  name: nauka-zdajmature
  github:
    branch: nauka-development
    deploy_on_push: true
    repo: WozniakMac/canvas-lms
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  - key: RAILS_SERVE_STATIC_FILES
    scope: RUN_TIME
    value: "true"
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-m
  routes:
  - path: /
  source_dir: /

databases:
- engine: PG
  name: db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
